/* ---------------- materials & geometry helpers ---------------- */
const MAT_CACHE = new Map();
function mat(color, o = {}) {
  const key = color + '|' + JSON.stringify(o);
  if (MAT_CACHE.has(key)) return MAT_CACHE.get(key);
  const m = new THREE.MeshStandardMaterial({ color: new THREE.Color(color), roughness: o.rough ?? 0.85, metalness: o.metal ?? 0.05, emissive: new THREE.Color(o.emissive || '#000000'), emissiveIntensity: o.ei ?? 1, transparent: !!o.transparent, opacity: o.opacity ?? 1, side: o.side || THREE.FrontSide, flatShading: !!o.flat });
  MAT_CACHE.set(key, m); return m;
}
function shade(hexc, f) { const c = new THREE.Color(hexc); c.multiplyScalar(f); return '#' + c.getHexString(); }
function mesh(geo, m, x = 0, y = 0, z = 0) { const o = new THREE.Mesh(geo, m); o.position.set(x, y, z); o.castShadow = true; o.receiveShadow = true; return o; }
const G = {
  box: (w, h, d) => new THREE.BoxGeometry(w, h, d),
  sph: (r, s = 12) => new THREE.SphereGeometry(r, s, Math.max(6, s - 2)),
  cyl: (rt, rb, h, s = 10) => new THREE.CylinderGeometry(rt, rb, h, s),
  cone: (r, h, s = 10) => new THREE.ConeGeometry(r, h, s),
  cap: (r, h) => new THREE.CapsuleGeometry(r, h, 3, 8),
  torus: (r, t) => new THREE.TorusGeometry(r, t, 8, 20),
  plane: (w, h) => new THREE.PlaneGeometry(w, h),
  ico: (r, d = 0) => new THREE.IcosahedronGeometry(r, d),
  dod: r => new THREE.DodecahedronGeometry(r, 0),
};
let _textures = {};
function textTexture(text, fg, bg) {
  const key = text + fg + bg; if (_textures[key]) return _textures[key];
  const c = document.createElement('canvas'); c.width = 512; c.height = 256; const x = c.getContext('2d');
  x.fillStyle = bg; x.fillRect(0, 0, 512, 256); x.fillStyle = fg; x.textAlign = 'center'; x.textBaseline = 'middle';
  let size = 88; x.font = `bold ${size}px Atkinson Hyperlegible, sans-serif`; while (x.measureText(text).width > 470 && size > 20) { size -= 6; x.font = `bold ${size}px Atkinson Hyperlegible, sans-serif`; }
  x.fillText(text, 256, 128); const t = new THREE.CanvasTexture(c); t.colorSpace = THREE.SRGBColorSpace; _textures[key] = t; return t;
}
function noiseTexture(seedColor, contrast = 0.12, rep = 40) {
  const key = 'n' + seedColor + contrast; if (_textures[key]) return _textures[key];
  const c = document.createElement('canvas'); c.width = c.height = 256; const x = c.getContext('2d'); const base = new THREE.Color(seedColor);
  const img = x.createImageData(256, 256); let s = 7;
  for (let i = 0; i < img.data.length; i += 4) { s = (s * 16807) % 2147483647; const n = 1 + ((s / 2147483647) - 0.5) * 2 * contrast; img.data[i] = clamp(base.r * 255 * n, 0, 255); img.data[i + 1] = clamp(base.g * 255 * n, 0, 255); img.data[i + 2] = clamp(base.b * 255 * n, 0, 255); img.data[i + 3] = 255; }
  x.putImageData(img, 0, 0); const t = new THREE.CanvasTexture(c); t.wrapS = t.wrapT = THREE.RepeatWrapping; t.repeat.set(rep, rep); t.colorSpace = THREE.SRGBColorSpace; _textures[key] = t; return t;
}
function windowTexture(color, lit) {
  const key = 'w' + color + lit; if (_textures[key]) return _textures[key];
  const c = document.createElement('canvas'); c.width = 128; c.height = 256; const x = c.getContext('2d'); x.fillStyle = color; x.fillRect(0, 0, 128, 256);
  let s = 3; for (let r = 0; r < 8; r++) for (let q = 0; q < 4; q++) { s = (s * 16807) % 2147483647; const on = lit && (s % 3 !== 0); x.fillStyle = on ? '#ffe9a8' : '#1d2230'; x.fillRect(12 + q * 28, 14 + r * 30, 18, 20); }
  const t = new THREE.CanvasTexture(c); t.wrapS = t.wrapT = THREE.RepeatWrapping; t.colorSpace = THREE.SRGBColorSpace; _textures[key] = t; return t;
}
function softSprite() { if (_textures.soft) return _textures.soft; const c = document.createElement('canvas'); c.width = c.height = 32; const x = c.getContext('2d'); const gr = x.createRadialGradient(16, 16, 0, 16, 16, 16); gr.addColorStop(0, 'rgba(255,255,255,1)'); gr.addColorStop(0.5, 'rgba(255,255,255,0.6)'); gr.addColorStop(1, 'rgba(255,255,255,0)'); x.fillStyle = gr; x.fillRect(0, 0, 32, 32); const t = new THREE.CanvasTexture(c); _textures.soft = t; return t; }
function seeded(seed) { let s = seed || 1; return () => { s = (s * 16807) % 2147483647; return (s - 1) / 2147483646; }; }

/* ---------------- actor builders: each returns a THREE.Group with userData.anim hooks ---------------- */
const B = {};
function humanoid(a, o = {}) {
  const g = new THREE.Group(); const col = a.color, skin = a.detail.skin || o.skin || '#e2b797', hair = a.detail.hair || o.hair || shade(col, 0.4);
  const body = mat(col, { transparent: a.ghost, opacity: a.ghost ? 0.45 : 1, emissive: o.emissive || (a.glow ? col : '#000'), ei: a.glow ? 0.6 : 1 });
  const skinM = mat(skin, { transparent: a.ghost, opacity: a.ghost ? 0.45 : 1 });
  const torso = mesh(G.cap(0.2, 0.5, 8), body, 0, 1.05, 0); torso.scale.set(1, 1, o.thin ? 0.6 : 0.8);
  const head = mesh(G.sph(0.14, 14), skinM, 0, 1.55, 0); const hairM = mesh(G.sph(0.162, 14), mat(hair), 0, 1.585, -0.02); hairM.scale.set(1, 0.72, 1); hairM.material = hairM.material.clone(); hairM.material.polygonOffset = true; hairM.material.polygonOffsetFactor = -1;
  const legs = [], arms = [];
  for (const sx of [-1, 1]) {
    const leg = new THREE.Group(); leg.position.set(sx * 0.1, 0.78, 0); leg.add(mesh(G.cap(0.075, 0.55, 6), mat(shade(col, 0.7)), 0, -0.36, 0)); g.add(leg); legs.push(leg);
    const arm = new THREE.Group(); arm.position.set(sx * 0.29, 1.32, 0); arm.add(mesh(G.cap(0.06, 0.5, 6), o.bare ? skinM : body, 0, -0.3, 0)); g.add(arm); arms.push(arm);
  }
  const eyes = new THREE.Group(); for (const sx of [-1, 1]) eyes.add(mesh(G.sph(0.02, 6), mat(o.eye || '#111'), sx * 0.05, 1.57, 0.125)); g.add(eyes);
  if (o.spikes) { for (let i = 0; i < 5; i++) g.add(mesh(G.cone(0.05, 0.25, 5), mat(shade(col, 0.6)), 0, 1.45 - i * 0.16, -0.2).rotateX(-1.2)); }
  g.add(torso, head, hairM); g.userData.limbs = { legs, arms, head, torso }; g.userData.height = 1.75; g.userData.eyeY = 1.55;
  return g;
}
B.person = a => humanoid(a);
B.ghost = a => humanoid({ ...a, ghost: true, glow: true }, { skin: '#e8ecff', hair: '#d0d6ff', eye: '#334' });
B.skeleton = a => humanoid({ ...a, color: '#eae6da' }, { skin: '#eae6da', hair: '#eae6da', thin: true, eye: '#000' });
B.monster = a => { const g = humanoid({ ...a, size: a.size }, { skin: shade(a.color, 0.8), hair: shade(a.color, 0.5), eye: '#ff2020', spikes: true }); g.scale.setScalar(1.6); g.userData.height = 2.8; g.userData.eyeY = 2.5; return g; };
B.crowd = a => { const g = new THREE.Group(); const n = a.detail.count || 12, r = a.detail.radius || Math.max(2, Math.sqrt(n) * 0.9), rnd = seeded(n * 7 + 3); g.userData.members = [];
  for (let i = 0; i < n; i++) { const ang = rnd() * Math.PI * 2, d = Math.sqrt(rnd()) * r; const p = humanoid({ ...a, color: shade(a.color, 0.7 + rnd() * 0.6), detail: {} }); p.position.set(Math.cos(ang) * d, 0, Math.sin(ang) * d); p.rotation.y = rnd() * 6.28; p.userData.phase = rnd() * 6.28; g.add(p); g.userData.members.push(p); }
  g.userData.height = 1.8; return g; };
const SPECIES = { dog: [0.9, 0.5, 0.35, 0.35, 0.22], cat: [0.5, 0.3, 0.22, 0.2, 0.15], horse: [1.9, 1.3, 0.9, 0.7, 0.45], wolf: [1.1, 0.65, 0.45, 0.4, 0.26], bear: [1.8, 1.1, 0.5, 0.5, 0.5], deer: [1.3, 1.0, 0.7, 0.45, 0.3], cow: [2.0, 1.2, 0.6, 0.5, 0.6], lion: [1.6, 0.9, 0.55, 0.5, 0.42], rat: [0.3, 0.12, 0.06, 0.1, 0.1], rabbit: [0.4, 0.25, 0.15, 0.15, 0.15], chimp: [0.7, 0.8, 0.5, 0.35, 0.3], generic: [1.0, 0.6, 0.4, 0.35, 0.28] };
B.animal = a => {
  const sp = a.detail.species || 'generic', g = new THREE.Group(), m = mat(a.color, { emissive: a.glow ? a.color : '#000', ei: 0.5 });
  if (sp === 'bird') { const body = mesh(G.sph(0.18, 10), m, 0, 1.6, 0); body.scale.set(0.8, 0.7, 1.4); const head = mesh(G.sph(0.1, 8), m, 0, 1.72, 0.25); const beak = mesh(G.cone(0.04, 0.15, 6), mat('#e0a030'), 0, 1.7, 0.38); beak.rotateX(1.57);
    const wings = []; for (const sx of [-1, 1]) { const w = new THREE.Group(); w.position.set(sx * 0.1, 1.65, 0); const wm = mesh(G.box(0.6, 0.03, 0.3), m, sx * 0.3, 0, 0); w.add(wm); g.add(w); wings.push(w); }
    g.add(body, head, beak); g.userData.wings = wings; g.userData.height = 2; g.userData.airborne = true; return g; }
  if (sp === 'fish') { const body = mesh(G.sph(0.25, 10), m, 0, 0.8, 0); body.scale.set(0.5, 0.8, 1.6); const tail = new THREE.Group(); tail.position.set(0, 0.8, -0.4); tail.add(mesh(G.cone(0.2, 0.3, 4), m, 0, 0, -0.15).rotateX(-1.57)); g.add(body, tail); g.userData.tail = tail; g.userData.height = 1; g.userData.airborne = true; return g; }
  if (sp === 'snake') { const segs = []; for (let i = 0; i < 10; i++) { const s = mesh(G.sph(0.12 - i * 0.006, 8), mat(i % 2 ? a.color : shade(a.color, 0.7)), 0, 0.12, -i * 0.2); g.add(s); segs.push(s); } g.userData.segs = segs; g.userData.height = 0.3; return g; }
  if (sp === 'spider') { const body = mesh(G.sph(0.25, 8), m, 0, 0.35, 0); const head = mesh(G.sph(0.15, 8), m, 0, 0.35, 0.3); g.add(body, head); const legs = []; for (let i = 0; i < 8; i++) { const sx = i < 4 ? -1 : 1; const l = new THREE.Group(); l.position.set(sx * 0.2, 0.35, (i % 4) * 0.15 - 0.2); const lm = mesh(G.cyl(0.02, 0.02, 0.6, 5), m, sx * 0.3, -0.1, 0); lm.rotation.z = sx * 1.2; l.add(lm); g.add(l); legs.push(l); } g.userData.legs = legs; g.userData.height = 0.6; return g; }
  const [len, h, legLen, headR, bodyR] = SPECIES[sp] || SPECIES.generic;
  const body = mesh(G.cap(bodyR, len - bodyR * 2, 8), m, 0, h, 0); body.rotation.x = Math.PI / 2;
  const neck = mesh(G.cyl(headR * 0.6, headR * 0.8, headR * 1.6, 8), m, 0, h + headR * 0.6, len / 2); neck.rotation.x = -0.6;
  const head = mesh(G.sph(headR, 10), m, 0, h + headR * 1.1, len / 2 + headR * 0.7); head.scale.set(0.8, 0.8, 1.2);
  const legs = []; for (const sx of [-1, 1]) for (const sz of [-1, 1]) { const l = new THREE.Group(); l.position.set(sx * bodyR * 0.7, h - bodyR * 0.5, sz * (len / 2 - bodyR * 0.9)); l.add(mesh(G.cyl(bodyR * 0.25, bodyR * 0.2, legLen + bodyR * 0.5, 6), m, 0, -(legLen + bodyR * 0.5) / 2, 0)); g.add(l); legs.push(l); }
  const tail = mesh(G.cyl(0.03, bodyR * 0.3, len * 0.5, 5), m, 0, h + bodyR * 0.3, -len / 2 - len * 0.2); tail.rotation.x = 1.2;
  for (const sx of [-1, 1]) g.add(mesh(G.sph(headR * 0.12, 5), mat('#111'), sx * headR * 0.45, h + headR * 1.3, len / 2 + headR * 1.5));
  g.add(body, neck, head, tail); g.userData.legs = legs; g.userData.height = h + headR * 2; return g;
};
B.hand = a => { const g = new THREE.Group(); const m = mat(a.color); g.add(mesh(G.box(0.9, 0.25, 1.0), m, 0, 0.6, 0)); for (let i = 0; i < 4; i++) g.add(mesh(G.cap(0.09, 0.6, 6), m, -0.33 + i * 0.22, 0.6, 0.85).rotateX(1.57)); g.add(mesh(G.cap(0.1, 0.45, 6), m, 0.6, 0.6, 0.2).rotateZ(-1.2)); g.userData.height = 1.2; return g; };
B.eye = a => { const g = new THREE.Group(); g.add(mesh(G.sph(0.5, 16), mat('#f4f4f4'), 0, 1.5, 0)); g.add(mesh(G.sph(0.22, 12), mat(a.color === '#f4f4f4' ? '#3a6ab0' : a.color), 0, 1.5, 0.38)); g.add(mesh(G.sph(0.1, 8), mat('#050505'), 0, 1.5, 0.52)); g.userData.height = 2; return g; };
B.tooth = a => { const g = new THREE.Group(); const m = mat(a.color, { rough: 0.35 }); const crown = mesh(G.cap(0.035, 0.03, 8), m, 0, 0.1, 0); crown.rotation.z = Math.PI / 2; crown.scale.set(1, 1.1, 0.9); g.add(crown); for (const sx of [-1, 1]) { const root = mesh(G.cone(0.02, 0.075, 7), m, sx * 0.022, 0.035, 0); root.rotation.x = Math.PI; g.add(root); } g.userData.height = 0.14; return g; };
B.house = a => { const g = new THREE.Group(); const w = a.detail.width || 8, d = a.detail.depth || 7, h = a.detail.height || 3.2; const wallM = mat(a.color); const box = mesh(G.box(w, h, d), wallM, 0, h / 2, 0); g.add(box);
  const roof = mesh(G.cyl(0, Math.max(w, d) * 0.72, h * 0.6, 4), mat(a.detail.second || shade(a.color, 0.45), { flat: true }), 0, h + h * 0.3, 0); roof.rotation.y = Math.PI / 4; roof.scale.set(w / Math.max(w, d), 1, d / Math.max(w, d)); g.add(roof);
  g.add(mesh(G.box(1, 2.1, 0.12), mat(shade(a.color, 0.35)), 0, 1.05, d / 2 + 0.06));
  const win = mat('#ffe9a8', { emissive: '#ffd27a', ei: 0.8 }); for (const sx of [-1, 1]) g.add(mesh(G.box(1.1, 1.1, 0.1), win, sx * w * 0.3, h * 0.55, d / 2 + 0.05));
  g.userData.height = h * 1.6; g.userData.big = true; return g; };
B.shop = a => { const g = B.house({ ...a, detail: { ...a.detail, width: a.detail.width || 7, depth: a.detail.depth || 6, height: a.detail.height || 3.4 } }); const d = a.detail.depth || 6; g.add(mesh(G.box(3.2, 1.6, 0.1), mat('#ffe9a8', { emissive: '#ffd27a', ei: 0.9 }), 1.5, 1.4, d / 2 + 0.06)); const t = a.detail.text || a.label; if (t) g.add(mesh(G.box(4.5, 0.9, 0.08), new THREE.MeshStandardMaterial({ map: textTexture(t, '#1a1a1a', a.detail.second || '#e8e0c0'), roughness: 0.8 }), 0, 3.0, d / 2 + 0.08)); return g; };
B.castle = a => { const g = new THREE.Group(); const m = mat(a.color, { flat: true }); g.add(mesh(G.box(3.2, 2.2, 3.2), m, 0, 1.1, 0)); for (const sx of [-1, 1]) for (const sz of [-1, 1]) { g.add(mesh(G.cyl(0.55, 0.6, 3.2, 8), m, sx * 1.5, 1.6, sz * 1.5)); g.add(mesh(G.cone(0.65, 0.8, 8), mat(shade(a.color, 0.7), { flat: true }), sx * 1.5, 3.6, sz * 1.5)); } for (let i = -1; i <= 1; i++) { g.add(mesh(G.box(0.4, 0.4, 0.3), m, i * 0.9, 2.4, 1.6)); g.add(mesh(G.box(0.4, 0.4, 0.3), m, i * 0.9, 2.4, -1.6)); } g.add(mesh(G.box(0.8, 1.2, 0.2), mat(shade(a.color, 0.35)), 0, 0.6, 1.65)); g.userData.height = 4; return g; };
B.church = a => { const g = B.house(a); const t = mesh(G.box(2.5, 9, 2.5), mat(a.color), -2.5, 4.5, -1); const spire = mesh(G.cone(1.8, 4, 4), mat(shade(a.color, 0.5)), -2.5, 11, -1); g.add(t, spire, mesh(G.box(0.15, 1, 0.15), mat('#d4af37'), -2.5, 13.5, -1), mesh(G.box(0.6, 0.15, 0.15), mat('#d4af37'), -2.5, 13.7, -1)); g.userData.height = 14; return g; };
B.building = a => { const g = new THREE.Group(); const w = a.detail.width || 10, d = a.detail.depth || 10, h = a.detail.height || 14; const tex = windowTexture(a.color, true); const m = new THREE.MeshStandardMaterial({ map: tex, roughness: 0.8, emissive: new THREE.Color('#665a30'), emissiveMap: tex, emissiveIntensity: 0.6 }); tex.repeat.set(Math.max(0.25, w / 12), Math.max(0.25, h / 24));
  const b = mesh(G.box(w, h, d), m, 0, h / 2, 0); g.add(b); g.add(mesh(G.box(w + 0.4, 0.4, d + 0.4), mat(shade(a.color, 0.6)), 0, h + 0.2, 0)); g.add(mesh(G.box(1.4, 2.4, 0.1), mat('#2a2a30'), 0, 1.2, d / 2 + 0.05)); g.userData.height = h; g.userData.big = true; return g; };
B.tower = a => { const g = new THREE.Group(); const h = a.detail.height || 22, r = (a.detail.width || 5) / 2; g.add(mesh(G.cyl(r * 0.9, r, h, 12), mat(a.color), 0, h / 2, 0)); g.add(mesh(G.cone(r * 1.2, h * 0.22, 12), mat(shade(a.color, 0.5)), 0, h + h * 0.11, 0)); for (let i = 1; i < 5; i++) g.add(mesh(G.box(0.6, 0.9, 0.1), mat('#ffe9a8', { emissive: '#ffd27a', ei: 0.7 }), 0, i * h / 5, r)); g.userData.height = h * 1.25; g.userData.big = true; return g; };
B.city = a => { const g = new THREE.Group(); const n = a.detail.count || 24, R = a.detail.radius || 60, rnd = seeded(n * 13 + 5); const tex = windowTexture(a.color, true); const m = new THREE.MeshStandardMaterial({ map: tex, roughness: 0.85, emissive: new THREE.Color('#5a5030'), emissiveMap: tex, emissiveIntensity: 0.5 });
  const im = new THREE.InstancedMesh(G.box(1, 1, 1), m, n); const M = new THREE.Matrix4(); for (let i = 0; i < n; i++) { const ang = rnd() * 6.28, d = 12 + Math.sqrt(rnd()) * R; const w = 6 + rnd() * 10, h = 8 + rnd() * rnd() * 60; M.makeScale(w, h, 6 + rnd() * 10); M.setPosition(Math.cos(ang) * d, h / 2, Math.sin(ang) * d); im.setMatrixAt(i, M); } im.castShadow = true; g.add(im); g.userData.height = 30; g.userData.big = true; g.userData.noScale = true; return g; };
B.room = a => { const g = new THREE.Group(); const w = a.detail.width || 8, d = a.detail.depth || 8, h = a.detail.height || 3; const wm = mat(a.color, { side: THREE.BackSide }); const inner = mesh(G.box(w, h, d), wm, 0, h / 2, 0); inner.castShadow = false; g.add(inner);
  const floor = mesh(G.plane(w, d), mat(a.detail.second || shade(a.color, 0.6)), 0, 0.02, 0); floor.rotation.x = -Math.PI / 2; g.add(floor);
  g.add(mesh(G.box(1, 2.1, 0.08), mat(shade(a.color, 0.4)), 0, 1.05, d / 2 - 0.05));
  const win = mesh(G.box(1.4, 1.1, 0.06), mat('#bcd8ff', { emissive: '#8fb0ff', ei: 0.5 }), -w / 2 + 0.04, 1.7, 0); win.rotation.y = Math.PI / 2; g.add(win);
  const lamp = new THREE.PointLight('#ffe0b0', 20, w + d, 1.6); lamp.position.set(0, h - 0.3, 0); g.add(lamp); g.add(mesh(G.sph(0.15, 8), mat('#fff4d0', { emissive: '#fff0c0', ei: 1.5 }), 0, h - 0.3, 0));
  g.userData.height = h; g.userData.big = true; g.userData.room = { w, d, h }; return g; };
B.wall = a => { const g = new THREE.Group(); g.add(mesh(G.box(a.detail.width || 6, a.detail.height || 2.5, 0.3), mat(a.color), 0, (a.detail.height || 2.5) / 2, 0)); g.userData.height = a.detail.height || 2.5; return g; };
B.fence = a => { const g = new THREE.Group(); const w = a.detail.width || 8, m = mat(a.color); for (let x = -w / 2; x <= w / 2; x += 1.2) g.add(mesh(G.box(0.12, 1.2, 0.12), m, x, 0.6, 0)); g.add(mesh(G.box(w, 0.1, 0.06), m, 0, 0.5, 0), mesh(G.box(w, 0.1, 0.06), m, 0, 1.0, 0)); g.userData.height = 1.2; return g; };
B.door = a => { const g = new THREE.Group(); const fm = mat(shade(a.color, 0.5)); g.add(mesh(G.box(0.12, 2.2, 0.15), fm, -0.56, 1.1, 0), mesh(G.box(0.12, 2.2, 0.15), fm, 0.56, 1.1, 0), mesh(G.box(1.24, 0.12, 0.15), fm, 0, 2.26, 0));
  const pivot = new THREE.Group(); pivot.position.set(-0.5, 0, 0); pivot.add(mesh(G.box(1, 2.2, 0.08), mat(a.color), 0.5, 1.1, 0)); pivot.add(mesh(G.sph(0.05, 6), mat('#d4af37'), 0.85, 1.05, 0.06)); g.add(pivot); g.userData.doorPivot = pivot; if (a.detail.open) pivot.rotation.y = -1.6; g.userData.height = 2.3; return g; };
B.window = a => { const g = new THREE.Group(); g.add(mesh(G.box(1.4, 1.2, 0.08), mat(a.color, { transparent: true, opacity: 0.5, emissive: '#6a90d0', ei: 0.3 }), 0, 1.6, 0)); g.add(mesh(G.box(1.5, 0.08, 0.1), mat('#5a4a3a'), 0, 2.2, 0), mesh(G.box(1.5, 0.08, 0.1), mat('#5a4a3a'), 0, 1.0, 0), mesh(G.box(0.08, 1.2, 0.1), mat('#5a4a3a'), -0.74, 1.6, 0), mesh(G.box(0.08, 1.2, 0.1), mat('#5a4a3a'), 0.74, 1.6, 0)); g.userData.height = 2.2; return g; };
B.stairs = a => { const g = new THREE.Group(); const n = 10, m = mat(a.color), h = (a.detail.height || 3) / n; for (let i = 0; i < n; i++) g.add(mesh(G.box(2, h, 0.35), m, 0, h * (i + 0.5), -i * 0.35)); g.userData.height = a.detail.height || 3; return g; };
B.ladder = a => { const g = new THREE.Group(); const h = a.detail.height || 4, m = mat(a.color); for (const sx of [-1, 1]) g.add(mesh(G.box(0.08, h, 0.08), m, sx * 0.3, h / 2, 0)); for (let y = 0.3; y < h; y += 0.4) g.add(mesh(G.box(0.6, 0.06, 0.06), m, 0, y, 0)); g.rotation.x = 0.15; g.userData.height = h; return g; };
B.corridor = a => { const g = new THREE.Group(); const w = a.detail.width || 3, d = a.detail.depth || 30, h = a.detail.height || 3; const m = mat(a.color, { side: THREE.BackSide }); const box = mesh(G.box(w, h, d), m, 0, h / 2, 0); box.castShadow = false; g.add(box); for (let z = -d / 2 + 3; z < d / 2; z += 6) { const l = new THREE.PointLight('#ffe8c0', 8, 10, 1.8); l.position.set(0, h - 0.3, z); g.add(l); g.add(mesh(G.box(0.6, 0.06, 0.2), mat('#fff', { emissive: '#fff', ei: 1.2 }), 0, h - 0.05, z)); } g.userData.height = h; g.userData.big = true; return g; };
B.elevator = a => { const g = new THREE.Group(); g.add(mesh(G.box(2.2, 2.6, 2.2), mat(a.color, { side: THREE.BackSide }), 0, 1.3, 0)); g.add(mesh(G.box(0.9, 2.2, 0.06), mat(shade(a.color, 0.7), { metal: 0.6, rough: 0.3 }), -0.46, 1.1, 1.1), mesh(G.box(0.9, 2.2, 0.06), mat(shade(a.color, 0.7), { metal: 0.6, rough: 0.3 }), 0.46, 1.1, 1.1)); g.userData.height = 2.6; return g; };
B.bridge = a => { const g = new THREE.Group(); const w = a.detail.width || 3, d = a.detail.depth || 20; g.add(mesh(G.box(w, 0.3, d), mat(a.color), 0, 0.15, 0)); const rm = mat(shade(a.color, 0.7)); for (const sx of [-1, 1]) { g.add(mesh(G.box(0.08, 1, d), rm, sx * (w / 2 - 0.05), 0.8, 0)); } g.userData.height = 1; g.userData.big = true; return g; };
function strip(a, wdef, ddef, col) { const g = new THREE.Group(); const w = a.detail.width || wdef, d = a.detail.depth || ddef; const p = mesh(G.plane(w, d), mat(col || a.color, { rough: 1 }), 0, 0.03, 0); p.rotation.x = -Math.PI / 2; p.castShadow = false; g.add(p); g.userData.height = 0.1; g.userData.flat = true; return g; }
B.road = a => { const g = strip(a, 8, 120); const lm = mat('#e8dfb0', { emissive: '#e8dfb0', ei: 0.2 }); const d = a.detail.depth || 120; for (let z = -d / 2; z < d / 2; z += 6) { const l = mesh(G.plane(0.25, 3), lm, 0, 0.04, z); l.rotation.x = -Math.PI / 2; l.castShadow = false; g.add(l); } return g; };
B.path = a => strip(a, 2, 60);
B.field = a => { const g = strip(a, (a.detail.radius || 30) * 2, (a.detail.radius || 30) * 2); const n = a.detail.count || 30, rnd = seeded(n + 11), R = a.detail.radius || 30; const im = new THREE.InstancedMesh(G.cone(0.15, 0.5, 4), mat(shade(a.color, 1.2)), n); const M = new THREE.Matrix4(); for (let i = 0; i < n; i++) { M.makeRotationY(rnd() * 6); M.setPosition((rnd() - 0.5) * R * 2, 0.25, (rnd() - 0.5) * R * 2); im.setMatrixAt(i, M); } g.add(im); return g; };
B.tent = a => { const g = new THREE.Group(); const p = mesh(G.cyl(1.9, 1.9, 4, 3), mat(a.color, { flat: true, side: THREE.DoubleSide }), 0, 0.95, 0); p.rotation.z = Math.PI / 2; p.rotation.y = 0; p.scale.set(1.25, 1, 1); g.add(p); g.add(mesh(G.box(0.9, 1.5, 0.05), mat('#1a1a20'), 0, 0.75, 2.02)); g.userData.height = 2.4; return g; };
B.grave = a => { const g = new THREE.Group(); const m = mat(a.color); g.add(mesh(G.box(0.8, 1.1, 0.15), m, 0, 0.55, 0), mesh(G.box(1.2, 0.2, 2.2), mat(shade(a.color, 0.6)), 0, 0.1, 1.1)); g.userData.height = 1.2; return g; };
function tree(color, second, rnd) { const g = new THREE.Group(); const h = 2.5 + rnd() * 2; g.add(mesh(G.cyl(0.12, 0.2, h, 6), mat(second || '#5a3d22'), 0, h / 2, 0)); const cm = mat(color, { flat: true }); if (rnd() < 0.5) { for (let i = 0; i < 3; i++) g.add(mesh(G.cone(1.6 - i * 0.4, 1.8, 7), cm, 0, h * 0.6 + i * 1.0, 0)); } else { const c = mesh(G.ico(1.5 + rnd(), 1), cm, 0, h + 0.8, 0); c.scale.y = 1.2; g.add(c); } g.userData.height = h + 2.5; g.userData.canopy = g.children.slice(1); return g; }
B.tree = a => { const rnd = seeded(a.id.length * 31 + 7); const g = tree(a.color, a.detail.second, rnd); return g; };
B.forest = a => { const g = new THREE.Group(); const n = a.detail.count || 30, R = a.detail.radius || 25, rnd = seeded(n * 17 + 1); g.userData.trees = []; for (let i = 0; i < n; i++) { const t = tree(shade(a.color, 0.75 + rnd() * 0.5), a.detail.second, rnd); const ang = rnd() * 6.28, d = 3 + Math.sqrt(rnd()) * R; t.position.set(Math.cos(ang) * d, 0, Math.sin(ang) * d); t.scale.setScalar(0.8 + rnd() * 0.8); g.add(t); g.userData.trees.push(t); } g.userData.height = 6; g.userData.big = true; g.userData.noScale = true; return g; };
B.bush = a => { const g = new THREE.Group(); const m = mat(a.color, { flat: true }); g.add(mesh(G.ico(0.7, 1), m, 0, 0.6, 0), mesh(G.ico(0.5, 1), m, 0.5, 0.45, 0.2), mesh(G.ico(0.5, 1), m, -0.4, 0.5, -0.3)); g.userData.height = 1.3; return g; };
B.flower = a => { const g = new THREE.Group(); const n = a.detail.count || 7, R = a.detail.radius || 1.2, rnd = seeded(n * 5 + 2); for (let i = 0; i < n; i++) { const x = (rnd() - 0.5) * R * 2, z = (rnd() - 0.5) * R * 2; g.add(mesh(G.cyl(0.02, 0.02, 0.5, 4), mat('#3f7a3a'), x, 0.25, z)); g.add(mesh(G.sph(0.09, 7), mat(i % 3 ? a.color : (a.detail.second || '#f4d35e'), { emissive: a.color, ei: 0.2 }), x, 0.52, z)); } g.userData.height = 0.7; return g; };
B.mountain = a => { const g = new THREE.Group(); const rnd = seeded(9); const m = mat(a.color, { flat: true }); for (let i = 0; i < 3; i++) { const h = 40 + rnd() * 40, r = h * 0.9; const c = mesh(G.cone(r, h, 7), m, (i - 1) * r * 1.1, h / 2, (rnd() - 0.5) * r); g.add(c); const snow = mesh(G.cone(r * 0.28, h * 0.28, 7), mat(a.detail.second || '#f0f4fa', { flat: true }), c.position.x, h - h * 0.14, c.position.z); g.add(snow); } g.userData.height = 80; g.userData.big = true; return g; };
B.hill = a => { const g = new THREE.Group(); const R = Math.min(60, (a.detail.radius || 20) * Math.min(a.size, 3)); const h = mesh(G.sph(R, 18), mat(a.color, { flat: true }), 0, -R * 0.7, 0); g.add(h); g.userData.height = R * 0.3; g.userData.big = true; g.userData.noScale = true; return g; };
B.rock = a => { const g = new THREE.Group(); const r = mesh(G.dod(0.8), mat(a.color, { flat: true }), 0, 0.6, 0); r.scale.set(1.3, 0.8, 1); g.add(r); g.userData.height = 1.3; return g; };
B.cliff = a => { const g = new THREE.Group(); const w = a.detail.width || 40, h = a.detail.height || 30, d = a.detail.depth || 20; g.add(mesh(G.box(w, h, d), mat(a.color, { flat: true }), 0, h / 2, -d / 2)); g.userData.height = h; g.userData.big = true; return g; };
B.cave = a => { const g = new THREE.Group(); const r = 3; const rockM = mat(a.color, { flat: true, side: THREE.DoubleSide }); const shell = new THREE.Mesh(new THREE.SphereGeometry(r * 2, 14, 10, Math.PI * 0.72, Math.PI * 1.56), rockM); shell.position.set(0, r * 0.2, -r * 1.2); shell.scale.set(1.3, 0.8, 1); shell.castShadow = true; g.add(shell); const inner = new THREE.Mesh(new THREE.SphereGeometry(r * 1.9, 14, 10, Math.PI * 0.72, Math.PI * 1.56), new THREE.MeshStandardMaterial({ color: '#2b2420', roughness: 1, side: THREE.BackSide })); inner.position.copy(shell.position); inner.scale.copy(shell.scale); g.add(inner); const l = new THREE.PointLight('#d9b080', 18, 26, 1.5); l.position.set(0, 2.5, -3); g.add(l); g.userData.height = r * 2; g.userData.big = true; g.userData.room = true; return g; };
B.pit = a => { const g = new THREE.Group(); const r = a.detail.radius || 1.5; const depth = a.detail.height || 4; const shaft = new THREE.Mesh(G.cyl(r, r * 0.8, depth, 20, 1, true), new THREE.MeshStandardMaterial({ color: '#3a342e', roughness: 1, side: THREE.BackSide })); shaft.position.y = -depth / 2; g.add(shaft); const floor = mesh(G.cyl(r * 0.8, r * 0.8, 0.05, 20), mat('#2a2622'), 0, -depth, 0); g.add(floor); const pl = new THREE.PointLight('#d9c0a0', 12, depth + r * 3, 1.4); pl.position.y = -depth * 0.5; g.add(pl); const cut = new THREE.Mesh(new THREE.CircleGeometry(r, 32), new THREE.MeshBasicMaterial({ colorWrite: false, depthWrite: false, stencilWrite: true, stencilRef: 1, stencilZPass: THREE.ReplaceStencilOp, stencilFunc: THREE.AlwaysStencilFunc })); cut.rotation.x = -Math.PI / 2; cut.position.y = 0.01; cut.renderOrder = -10; g.add(cut); g.add(mesh(G.torus(r, 0.12), mat(a.color === '#0a0a0c' ? '#5a5048' : a.color), 0, 0.05, 0).rotateX(1.57)); g.userData.height = 0.2; g.userData.flat = true; return g; };
function waterMaterial(color) { const m = new THREE.MeshStandardMaterial({ color: new THREE.Color(color), roughness: 0.25, metalness: 0.3, transparent: true, opacity: 0.9, polygonOffset: true, polygonOffsetFactor: -2, polygonOffsetUnits: -2 }); m.onBeforeCompile = sh => { sh.uniforms.uTime = { value: 0 }; m.userData.sh = sh; sh.vertexShader = 'uniform float uTime;\n' + sh.vertexShader.replace('#include <begin_vertex>', '#include <begin_vertex>\n transformed.z += sin(position.x * 0.6 + uTime * 1.3) * 0.04 + sin(position.y * 0.9 + uTime * 0.9) * 0.03;'); }; m.userData.water = true; return m; }
B.water = a => { const g = new THREE.Group(); const R = a.detail.radius || 15; const p = mesh(new THREE.RingGeometry(0.001, R, 48, Math.min(40, Math.max(8, Math.round(R / 1.5)))), waterMaterial(a.color), 0, 0.09, 0); p.rotation.x = -Math.PI / 2; p.castShadow = false; g.add(p); g.userData.height = 0.1; g.userData.flat = true; g.userData.big = true; return g; };
B.river = a => { const g = new THREE.Group(); const w = a.detail.width || 8, d = a.detail.depth || 120; const p = mesh(new THREE.PlaneGeometry(w, d, 8, 60), waterMaterial(a.color), 0, 0.09, 0); p.rotation.x = -Math.PI / 2; p.castShadow = false; g.add(p); g.userData.height = 0.1; g.userData.flat = true; g.userData.big = true; return g; };
B.cloud = a => { const g = new THREE.Group(); const m = mat(a.color, { transparent: true, opacity: 0.85, rough: 1 }); const rnd = seeded(a.id.length + 4); for (let i = 0; i < 5; i++) { const s = mesh(G.sph(1.2 + rnd() * 1.2, 10), m, (i - 2) * 1.6, 12 + rnd() * 0.6, (rnd() - 0.5) * 1.5); s.castShadow = false; g.add(s); } g.userData.height = 14; g.userData.drift = true; g.userData.airborne = true; return g; };
B.moon = a => { const g = new THREE.Group(); const m = new THREE.MeshBasicMaterial({ color: new THREE.Color(a.color), fog: false }); const d = mesh(G.sph(5, 24), m, 0, 0, 0); d.castShadow = false; g.add(d); const l = new THREE.PointLight(a.color, 400, 260, 1.2); g.add(l); g.userData.height = 5; g.userData.airborne = true; g.userData.far = true; g.userData.noColor = true; g.userData.centered = true; return g; };
B.sun = a => { const g = new THREE.Group(); const m = new THREE.MeshBasicMaterial({ color: new THREE.Color(a.color), fog: false }); const d = mesh(G.sph(7, 24), m, 0, 0, 0); d.castShadow = false; g.add(d); g.userData.height = 7; g.userData.airborne = true; g.userData.far = true; g.userData.noColor = true; g.userData.centered = true; return g; };
B.star = a => { const g = new THREE.Group(); g.add(mesh(G.ico(0.4, 0), new THREE.MeshBasicMaterial({ color: new THREE.Color(a.color), fog: false }), 0, 1.5, 0)); g.userData.height = 2; g.userData.airborne = true; g.userData.pulse = true; return g; };
B.orb = a => { const g = new THREE.Group(); g.add(mesh(G.sph(0.5, 16), mat(a.color, { emissive: a.color, ei: 1.0, transparent: true, opacity: 0.9 }), 0, 1.4, 0)); const l = new THREE.PointLight(a.color, 12, 12, 1.8); l.position.y = 1.4; g.add(l); g.userData.height = 2; g.userData.airborne = true; g.userData.pulse = true; return g; };
B.portal = a => { const g = new THREE.Group(); g.add(mesh(G.torus(1.4, 0.15), mat(a.color, { emissive: a.color, ei: 1.2 }), 0, 1.6, 0)); g.add(mesh(new THREE.CircleGeometry(1.3, 24), mat(shade(a.color, 0.4), { emissive: a.color, ei: 0.5, transparent: true, opacity: 0.7, side: THREE.DoubleSide }), 0, 1.6, 0)); const l = new THREE.PointLight(a.color, 15, 12, 1.8); l.position.y = 1.6; g.add(l); g.userData.height = 3.2; g.userData.spinPart = g.children[0]; return g; };
B.fire = a => { const g = new THREE.Group(); const fm = mat(a.color, { emissive: a.color, ei: 1.5, transparent: true, opacity: 0.9 }); const flames = []; for (let i = 0; i < 4; i++) { const f = mesh(G.cone(0.35 - i * 0.05, 1.0 + i * 0.2, 6), fm, (i - 1.5) * 0.18, 0.5 + i * 0.1, 0); f.castShadow = false; g.add(f); flames.push(f); } for (let i = 0; i < 3; i++) g.add(mesh(G.cyl(0.06, 0.06, 0.9, 5), mat('#3a2a1a'), 0, 0.06, 0).rotateZ(1.57).rotateX(i * 1.05)); const l = new THREE.PointLight('#ff9040', 30, 18, 1.6); l.position.y = 0.8; g.add(l); g.userData.flames = flames; g.userData.light = l; g.userData.height = 1.6; return g; };
B.smoke = a => { const g = new THREE.Group(); const m = mat(a.color, { transparent: true, opacity: 0.35, rough: 1 }); const puffs = []; for (let i = 0; i < 6; i++) { const p = mesh(G.sph(0.6 + i * 0.25, 8), m, (i % 2 ? 0.4 : -0.4) * (i / 3), 0.8 + i * 0.9, 0); p.castShadow = false; g.add(p); puffs.push(p); } g.userData.puffs = puffs; g.userData.height = 6; return g; };
B.lamp = a => { const g = new THREE.Group(); const h = a.detail.height || 4; g.add(mesh(G.cyl(0.06, 0.09, h, 6), mat('#3a3a40'), 0, h / 2, 0)); g.add(mesh(G.box(0.5, 0.1, 0.5), mat('#3a3a40'), 0, h, 0)); g.add(mesh(G.sph(0.22, 10), mat(a.color, { emissive: a.color, ei: 1.5 }), 0, h - 0.2, 0)); const l = new THREE.PointLight(a.color, 25, 16, 1.5); l.position.set(0, h - 0.3, 0); l.castShadow = false; g.add(l); g.userData.height = h; return g; };
B.candle = a => { const g = new THREE.Group(); g.add(mesh(G.cyl(0.05, 0.05, 0.3, 8), mat('#f4ecd8'), 0, 0.9, 0)); const f = mesh(G.cone(0.03, 0.12, 6), mat('#ffcc60', { emissive: '#ffb030', ei: 2 }), 0, 1.11, 0); g.add(f); const l = new THREE.PointLight('#ffb060', 6, 6, 1.8); l.position.y = 1.1; g.add(l); g.userData.flames = [f]; g.userData.height = 1.2; return g; };
function wheels(g, m, pts, r) { const ws = []; for (const [x, z] of pts) { const w = mesh(G.cyl(r, r, 0.3, 12), m, x, r, z); w.rotation.z = Math.PI / 2; g.add(w); ws.push(w); } g.userData.wheels = ws; }
B.car = a => { const g = new THREE.Group(); const m = mat(a.color, { rough: 0.4, metal: 0.3 }); g.add(mesh(G.box(1.9, 0.6, 4.2), m, 0, 0.75, 0)); g.add(mesh(G.box(1.7, 0.6, 2.2), mat(a.detail.second || '#9fc8e8', { rough: 0.2, metal: 0.5 }), 0, 1.35, -0.2)); wheels(g, mat('#222'), [[-0.95, 1.3], [0.95, 1.3], [-0.95, -1.3], [0.95, -1.3]], 0.38); for (const sx of [-1, 1]) g.add(mesh(G.sph(0.1, 6), mat('#fff', { emissive: '#fff8d0', ei: 2 }), sx * 0.7, 0.8, 2.1)); g.userData.height = 1.7; return g; };
B.bus = a => { const g = new THREE.Group(); g.add(mesh(G.box(2.5, 2.6, 10), mat(a.color, { rough: 0.5 }), 0, 1.7, 0)); const wm = mat('#bcd8ff', { emissive: '#8fb0ff', ei: 0.3 }); for (let z = -4; z <= 4; z += 1.6) for (const sx of [-1, 1]) g.add(mesh(G.box(0.05, 1, 1.2), wm, sx * 1.26, 2.1, z)); wheels(g, mat('#222'), [[-1.2, 3.2], [1.2, 3.2], [-1.2, -3.2], [1.2, -3.2]], 0.5); g.userData.height = 3; return g; };
B.truck = a => { const g = new THREE.Group(); g.add(mesh(G.box(2.4, 2.4, 5), mat(a.color), 0, 1.7, -1.5)); g.add(mesh(G.box(2.2, 1.8, 2), mat(shade(a.color, 0.7)), 0, 1.3, 2.4)); wheels(g, mat('#222'), [[-1.2, 2.2], [1.2, 2.2], [-1.2, -2.2], [1.2, -2.2]], 0.5); g.userData.height = 2.9; return g; };
B.train = a => { const g = new THREE.Group(); const m = mat(a.color, { rough: 0.5, metal: 0.3 }); for (let i = 0; i < 4; i++) { g.add(mesh(G.box(2.6, 2.8, 8), i ? mat(shade(a.color, 0.8)) : m, 0, 1.9, -i * 8.6)); for (const sx of [-1, 1]) for (const z of [-3, 3]) g.add(mesh(G.cyl(0.45, 0.45, 0.3, 10), mat('#222'), sx * 1.2, 0.45, -i * 8.6 + z).rotateZ(1.57)); } g.add(mesh(G.cyl(0.3, 0.3, 1.2, 8), mat('#222'), 0, 3.8, 2.5)); g.userData.height = 3.5; g.userData.big = true; return g; };
B.plane = a => { const g = new THREE.Group(); const m = mat(a.color, { rough: 0.3, metal: 0.4 }); g.add(mesh(G.cap(0.7, 7, 8), m, 0, 3, 0).rotateX(1.57)); g.add(mesh(G.box(12, 0.15, 1.8), m, 0, 3, 0.3)); g.add(mesh(G.box(3.5, 0.12, 1), m, 0, 3, -3.8)); g.add(mesh(G.box(0.12, 1.8, 1.2), m, 0, 3.9, -3.9)); g.userData.height = 4.5; g.userData.airborne = true; g.userData.big = true; return g; };
B.helicopter = a => { const g = new THREE.Group(); const m = mat(a.color, { rough: 0.5 }); const body = mesh(G.sph(1.2, 12), m, 0, 2, 0); body.scale.set(0.8, 0.8, 1.4); g.add(body); g.add(mesh(G.box(0.4, 0.4, 4), m, 0, 2.3, -3)); g.add(mesh(G.box(0.1, 1, 0.8), m, 0, 2.9, -5)); g.add(mesh(G.box(1.7, 0.9, 0.05), mat('#9fc8e8', { rough: 0.2 }), 0, 2.2, 1.6)); const rotor = mesh(G.box(9, 0.06, 0.3), mat('#222'), 0, 3.1, 0); g.add(rotor); g.add(mesh(G.cyl(0.08, 0.08, 0.5, 6), mat('#222'), 0, 2.9, 0)); for (const sx of [-1, 1]) g.add(mesh(G.cyl(0.06, 0.06, 3, 6), mat('#222'), sx * 0.8, 0.9, 0).rotateX(1.57)); g.userData.rotor = rotor; g.userData.height = 3.2; g.userData.airborne = true; g.userData.big = true; return g; };
B.boat = a => { const g = new THREE.Group(); const hull = mesh(G.cyl(1.4, 0.6, 6, 8), mat(a.color), 0, 0.6, 0); hull.rotation.x = Math.PI / 2; hull.scale.set(1, 1, 0.8); g.add(hull); g.add(mesh(G.cyl(0.06, 0.06, 6, 6), mat('#5a3d22'), 0, 3.6, 0)); g.add(mesh(G.plane(2.6, 3.2), mat(a.detail.second || '#f0ecd8', { side: THREE.DoubleSide }), 0.02, 4.6, -0.6).rotateY(1.57)); g.userData.height = 6.5; g.userData.bob = true; return g; };
B.bike = a => { const g = new THREE.Group(); const m = mat(a.color); wheels(g, mat('#222'), [[0, 0.55], [0, -0.55]], 0.35); g.add(mesh(G.box(0.05, 0.06, 1.0), m, 0, 0.6, 0), mesh(G.box(0.05, 0.6, 0.06), m, 0, 0.7, -0.2), mesh(G.box(0.5, 0.05, 0.05), m, 0, 1.0, 0.5)); g.userData.height = 1; return g; };
B.bed = a => { const g = new THREE.Group(); g.add(mesh(G.box(1.6, 0.35, 2.1), mat(shade(a.color, 0.6)), 0, 0.3, 0)); g.add(mesh(G.box(1.5, 0.2, 2.0), mat(a.color), 0, 0.55, 0)); g.add(mesh(G.box(1.2, 0.15, 0.5), mat('#f4f1ea'), 0, 0.72, -0.7)); g.add(mesh(G.box(1.6, 0.9, 0.08), mat(shade(a.color, 0.5)), 0, 0.6, -1.06)); g.userData.height = 1; return g; };
B.table = a => { const g = new THREE.Group(); const w = a.detail.width || 1.6, d = a.detail.depth || 0.9; const m = mat(a.color); g.add(mesh(G.box(w, 0.06, d), m, 0, 0.75, 0)); for (const sx of [-1, 1]) for (const sz of [-1, 1]) g.add(mesh(G.box(0.06, 0.72, 0.06), m, sx * (w / 2 - 0.08), 0.36, sz * (d / 2 - 0.08))); g.userData.height = 0.8; return g; };
B.desk = a => { const g = B.table({ ...a, detail: { width: 1.4, depth: 0.7 } }); g.add(mesh(G.box(0.5, 0.5, 0.6), mat(shade(a.color, 0.7)), 0.4, 0.25, 0)); return g; };
B.chair = a => { const g = new THREE.Group(); const m = mat(a.color); g.add(mesh(G.box(0.45, 0.05, 0.45), m, 0, 0.45, 0), mesh(G.box(0.45, 0.5, 0.05), m, 0, 0.72, -0.2)); for (const sx of [-1, 1]) for (const sz of [-1, 1]) g.add(mesh(G.box(0.04, 0.45, 0.04), m, sx * 0.19, 0.22, sz * 0.19)); g.userData.height = 1; return g; };
B.sofa = a => { const g = new THREE.Group(); const m = mat(a.color); g.add(mesh(G.box(2, 0.45, 0.9), m, 0, 0.3, 0), mesh(G.box(2, 0.5, 0.25), m, 0, 0.75, -0.33), mesh(G.box(0.25, 0.3, 0.9), m, -0.9, 0.65, 0), mesh(G.box(0.25, 0.3, 0.9), m, 0.9, 0.65, 0)); g.userData.height = 1; return g; };
B.mirror = a => { const g = new THREE.Group(); g.add(mesh(G.box(1.1, 1.7, 0.06), mat('#5a4a3a'), 0, 1.3, 0)); g.add(mesh(G.box(1.0, 1.6, 0.02), mat(a.color, { rough: 0.05, metal: 0.95, emissive: '#223', ei: 0.4 }), 0, 1.3, 0.04)); g.userData.height = 2.2; return g; };
B.phone = a => { const g = new THREE.Group(); g.add(mesh(G.box(0.08, 0.16, 0.01), mat(a.color, { rough: 0.3 }), 0, 1.0, 0)); g.add(mesh(G.box(0.07, 0.14, 0.005), mat('#bcd8ff', { emissive: '#8fb0ff', ei: 1 }), 0, 1.0, 0.007)); g.userData.height = 1.1; g.userData.airborne = true; return g; };
B.book = a => { const g = new THREE.Group(); g.add(mesh(G.box(0.3, 0.05, 0.4), mat(a.color), 0, 0.8, 0)); g.add(mesh(G.box(0.28, 0.03, 0.38), mat('#f4f1ea'), 0, 0.84, 0)); g.userData.height = 0.9; g.userData.airborne = true; return g; };
B.sign = a => { const g = new THREE.Group(); const t = a.detail.text || a.label || ''; g.add(mesh(G.cyl(0.05, 0.05, 2.2, 6), mat('#4a4a50'), 0, 1.1, 0)); const p = mesh(G.box(2, 1, 0.06), t ? new THREE.MeshStandardMaterial({ map: textTexture(t, '#1a1a1a', a.color), roughness: 0.8 }) : mat(a.color), 0, 2.6, 0); g.add(p); g.userData.height = 3.1; return g; };
B.tv = a => { const g = new THREE.Group(); g.add(mesh(G.box(1.2, 0.7, 0.08), mat(a.color), 0, 1.0, 0)); g.add(mesh(G.box(1.1, 0.6, 0.02), mat('#8fb0ff', { emissive: '#8fb0ff', ei: 1.2 }), 0, 1.0, 0.05)); g.add(mesh(G.box(0.4, 0.6, 0.4), mat(shade(a.color, 0.8)), 0, 0.3, 0)); g.userData.height = 1.4; g.userData.pulse = true; return g; };
B.computer = a => { const g = new THREE.Group(); g.add(mesh(G.box(0.6, 0.4, 0.05), mat(a.color), 0, 1.0, 0)); g.add(mesh(G.box(0.55, 0.35, 0.02), mat('#8fb0ff', { emissive: '#8fb0ff', ei: 1 }), 0, 1.0, 0.03)); g.add(mesh(G.box(0.5, 0.02, 0.2), mat('#333'), 0, 0.77, 0.3)); g.userData.height = 1.2; return g; };
B.clock = a => { const g = new THREE.Group(); g.add(mesh(G.cyl(0.4, 0.4, 0.08, 20), mat(a.color), 0, 2, 0).rotateX(1.57)); g.add(mesh(G.box(0.03, 0.3, 0.02), mat('#111'), 0, 2.12, 0.05)); const h = mesh(G.box(0.03, 0.22, 0.02), mat('#111'), 0.08, 2.05, 0.05); h.rotation.z = -1; g.add(h); g.userData.height = 2.5; return g; };
B.key = a => { const g = new THREE.Group(); const m = mat(a.color, { metal: 0.8, rough: 0.3 }); g.add(mesh(G.torus(0.12, 0.03), m, 0, 1.2, 0), mesh(G.box(0.04, 0.3, 0.02), m, 0, 0.95, 0), mesh(G.box(0.1, 0.05, 0.02), m, 0.05, 0.85, 0)); g.userData.height = 1.4; g.userData.airborne = true; return g; };
B.ring = a => { const g = new THREE.Group(); g.add(mesh(G.torus(0.25, 0.05), mat(a.color, { metal: 0.9, rough: 0.2, emissive: a.color, ei: 0.2 }), 0, 1.2, 0)); g.userData.height = 1.5; g.userData.airborne = true; g.userData.spinPart = g.children[0]; return g; };
B.balloon = a => { const g = new THREE.Group(); g.add(mesh(G.sph(0.35, 12), mat(a.color, { rough: 0.3 }), 0, 2.4, 0)); g.add(mesh(G.cyl(0.005, 0.005, 1.6, 4), mat('#ddd'), 0, 1.3, 0)); g.userData.height = 2.8; g.userData.airborne = true; g.userData.bob = true; return g; };
B.umbrella = a => { const g = new THREE.Group(); g.add(mesh(G.cyl(0.015, 0.015, 1, 5), mat('#333'), 0, 1.3, 0)); g.add(mesh(new THREE.SphereGeometry(0.9, 12, 6, 0, 6.29, 0, 1.2), mat(a.color, { side: THREE.DoubleSide }), 0, 1.5, 0)); g.userData.height = 2.4; return g; };
B.food = a => { const g = new THREE.Group(); g.add(mesh(G.cyl(0.3, 0.3, 0.03, 16), mat('#f4f1ea'), 0, 0.78, 0)); g.add(mesh(G.sph(0.14, 8), mat(a.color), 0, 0.9, 0), mesh(G.sph(0.1, 8), mat(shade(a.color, 0.7)), 0.15, 0.85, 0.1)); g.userData.height = 1.0; return g; };
B.bag = a => { const g = new THREE.Group(); g.add(mesh(G.box(0.5, 0.45, 0.25), mat(a.color), 0, 0.25, 0)); g.add(mesh(G.torus(0.15, 0.02), mat(shade(a.color, 0.6)), 0, 0.5, 0)); g.userData.height = 0.7; return g; };
B.gun = a => { const g = new THREE.Group(); const m = mat(a.color, { metal: 0.7, rough: 0.35 }); g.add(mesh(G.box(0.06, 0.06, 0.9), m, 0, 1.2, 0.3), mesh(G.box(0.07, 0.18, 0.35), mat('#5a3d22'), 0, 1.1, -0.2)); g.userData.height = 1.3; g.userData.airborne = true; return g; };
B.knife = a => { const g = new THREE.Group(); g.add(mesh(G.box(0.03, 0.5, 0.005), mat(a.color, { metal: 0.9, rough: 0.2 }), 0, 1.35, 0), mesh(G.box(0.04, 0.2, 0.03), mat('#3a2a1a'), 0, 1.0, 0)); g.userData.height = 1.6; g.userData.airborne = true; return g; };
B.box = a => { const g = new THREE.Group(); const w = a.detail.width || 1, h = a.detail.height || 1, d = a.detail.depth || 1; g.add(mesh(G.box(w, h, d), mat(a.color, { emissive: a.glow ? a.color : '#000', ei: 0.6 }), 0, h / 2, 0)); g.userData.height = h; return g; };
B.sphere = a => { const g = new THREE.Group(); g.add(mesh(G.sph(0.6, 16), mat(a.color, { emissive: a.glow ? a.color : '#000', ei: 0.6 }), 0, 0.6, 0)); g.userData.height = 1.2; return g; };
B.cylinder = a => { const g = new THREE.Group(); const h = a.detail.height || 3; g.add(mesh(G.cyl(0.5, 0.5, h, 14), mat(a.color), 0, h / 2, 0)); g.userData.height = h; return g; };
B.pyramid = a => { const g = new THREE.Group(); const h = a.detail.height || 3; g.add(mesh(G.cone(h * 0.8, h, 4), mat(a.color, { flat: true }), 0, h / 2, 0).rotateY(0.78)); g.userData.height = h; return g; };
B.thing = a => { const g = new THREE.Group(); const t = mesh(G.dod(0.32), mat(a.color, { flat: true, emissive: a.color, ei: 0.15 }), 0, 0.3, 0); g.add(t); g.userData.height = 0.6; g.userData.spinPart = t; return g; };

const SOFT = new Set(['person', 'crowd', 'monster', 'skeleton', 'ghost']);
const SOLID = new Set(['house', 'shop', 'building', 'tower', 'castle', 'church', 'wall', 'hill', 'mountain', 'rock', 'cliff', 'cave', 'tent', 'room', 'corridor', 'elevator', 'bus', 'train', 'truck']);
function buildActor(a) {
  let g; try { g = (B[a.kind] || B.thing)(a); } catch (e) { console.warn('builder failed', a.kind, e); g = B.thing(a); }
  if (SOFT.has(a.kind)) g.traverse(o => { if (o.isMesh && o.geometry.type === 'CapsuleGeometry') { o.userData.solid = true; o.userData.soft = true; } });
  if (SOLID.has(a.kind)) g.traverse(o => { if (o.isMesh && !o.isInstancedMesh && !(o.material.side === THREE.BackSide && a.kind !== 'room' && a.kind !== 'corridor')) o.userData.solid = true; });
  if (!g.userData.noScale) g.scale.setScalar(a.size); else g.scale.setScalar(1);
  g.userData.actor = a; g.userData.baseHeight = (g.userData.height || 1.8) * (g.userData.noScale ? 1 : a.size);
  g.traverse(o => { if (o.isMesh && a.ghost && !o.material.userData.water) { o.material = o.material.clone(); o.material.transparent = true; o.material.opacity = Math.min(o.material.opacity, 0.45); o.castShadow = false; } });
  return g;
}
